[package]
name = "tachibana"
version = "0.1.0"
authors = ["Dmitri Melnikov"]
license = "CC0-1.0"
edition = "2018"

[dependencies]
image = "0.20"
rand = "0.6"
xoshiro = "0.0.4"
rayon = "1.0"

[profile.release]
debug = true # for profiling
lto = true
